FROM python:3.12-slim

LABEL maintainer='martin.mulone@moneyonchain.com'

ENV PYTHONUNBUFFERED=1

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

RUN mkdir /home/app && useradd -r -d /home/app appuser

WORKDIR /home/app/
COPY api/ ./api/

ENV PATH="$PATH:/home/app/"
ENV PYTHONPATH="/home/app/"

USER appuser

EXPOSE 5005

CMD ["uvicorn", "api.app:app", "--host", "0.0.0.0", "--port", "5005"]