FROM nginx:1.31.1

# configuration
COPY ./nginx/nginx.conf /etc/nginx/nginx.conf


# Append "daemon off;" to the beginning of the configuration
RUN echo "daemon off;" >> /etc/nginx/nginx.conf

EXPOSE 80

CMD service nginx start

